apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-sistema-deployment
spec:
  selector:
    matchLabels:
      name: aplicacao-sistema-pod
  template:
    metadata:
      labels:
        name: aplicacao-sistema-pod
    spec:
      containers:
        - name: container-aplicacao-sistema
          image: bernardcg/noticia-alura:sv1
          ports:
            - containerPort: 80

---
# ==============
# = Service LB =
# ==============

apiVersion: v1
kind: Service
metadata:
  name: servico-aplicacao-sistema
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    name: aplicacao-sistema-pod
