apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-noticia-deployment
spec:
  selector:
    matchLabels:
      name: aplicacao-noticia-pod
  template:
    metadata:
      labels:
        name: aplicacao-noticia-pod
    spec:
      containers:
        - name: container-aplicacao
          image: bernardcg/noticia-alura:nv2
          resources:
            requests:
              cpu: 400m
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command: ["sh","notificacao.sh"]

---
# ==============
# = Service LB =
# ==============

apiVersion: v1
kind: Service
metadata:
  name: servico-aplicacao-noticia
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    name: aplicacao-noticia-pod
